/* Guess the Cricketer - player database. Facts only.
 * role = ESPNcricinfo Playing Role (verbatim). ipls = all IPL franchises, chronological earliest->latest
 * (last = current/most-recent team). wc = WON | SQUAD | NEVER (World Cup). Franchise codes incl. defunct
 * KTK PWI RPS GL DECCAN. IPL Mode pool = non-empty ipls; Legend Mode = all.
 */
(function (root) {
  var C = [
    // ---------- INDIA ----------
    { name: "Virat Kohli", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2008, ipls: ["RCB"], wc: "WON" },
    { name: "Rohit Sharma", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipls: ["DECCAN","MI"], wc: "WON" },
    { name: "MS Dhoni", country: "India", role: "Keeper", bat: "Right", bowl: "Right-arm medium", debut: 2004, ipls: ["CSK","RPS"], wc: "WON" },
    { name: "Sachin Tendulkar", country: "India", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 1989, ipls: ["MI"], wc: "WON" },
    { name: "Rahul Dravid", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1996, ipls: ["RCB","RR"], wc: "SQUAD" },
    { name: "Sourav Ganguly", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1992, ipls: ["KKR","PWI"], wc: "SQUAD" },
    { name: "VVS Laxman", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1996, ipls: ["DECCAN","KTK","SRH"], wc: "NEVER" },
    { name: "Virender Sehwag", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipls: ["DC","PBKS"], wc: "WON" },
    { name: "Yuvraj Singh", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2000, ipls: ["PBKS","PWI","RCB","DC","SRH","MI"], wc: "WON" },
    { name: "Gautam Gambhir", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2003, ipls: ["DC","KKR"], wc: "WON" },
    { name: "Zaheer Khan", country: "India", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2000, ipls: ["RCB","MI","DC"], wc: "WON" },
    { name: "Harbhajan Singh", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1998, ipls: ["MI","CSK","KKR"], wc: "WON" },
    { name: "Anil Kumble", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1990, ipls: ["RCB"], wc: "SQUAD" },
    { name: "Jasprit Bumrah", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipls: ["MI"], wc: "WON" },
    { name: "Ravindra Jadeja", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2009, ipls: ["KTK","CSK","GL","RR"], wc: "WON" },
    { name: "Ravichandran Ashwin", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2010, ipls: ["CSK","RPS","PBKS","DC","RR"], wc: "WON" },
    { name: "KL Rahul", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2014, ipls: ["RCB","SRH","PBKS","LSG","DC"], wc: "SQUAD" },
    { name: "Shikhar Dhawan", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2010, ipls: ["DC","MI","DECCAN","SRH","PBKS"], wc: "SQUAD" },
    { name: "Rishabh Pant", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2017, ipls: ["DC","LSG"], wc: "WON" },
    { name: "Shreyas Iyer", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2017, ipls: ["DC","KKR","PBKS"], wc: "SQUAD" },
    { name: "Hardik Pandya", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipls: ["MI","GT"], wc: "WON" },
    { name: "Mohammed Shami", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2013, ipls: ["KKR","DC","PBKS","GT","SRH","LSG"], wc: "SQUAD" },
    { name: "Bhuvneshwar Kumar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2012, ipls: ["RCB","PWI","SRH"], wc: "SQUAD" },
    { name: "Yuzvendra Chahal", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2016, ipls: ["MI","RCB","RR","PBKS"], wc: "WON" },
    { name: "Kuldeep Yadav", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm wrist-spin", debut: 2017, ipls: ["KKR","DC","LSG"], wc: "WON" },
    { name: "Suryakumar Yadav", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2021, ipls: ["MI","KKR"], wc: "WON" },
    { name: "Shubman Gill", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2019, ipls: ["KKR","GT"], wc: "SQUAD" },
    { name: "Mohammed Siraj", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2017, ipls: ["SRH","RCB","GT"], wc: "WON" },
    { name: "Ishant Sharma", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2007, ipls: ["KKR","DECCAN","SRH","RPS","PBKS","DC","GT"], wc: "SQUAD" },
    { name: "Cheteshwar Pujara", country: "India", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipls: ["KKR","RCB","PBKS","CSK"], wc: "NEVER" },
    { name: "Ajinkya Rahane", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2011, ipls: ["MI","RR","RPS","DC","KKR","CSK"], wc: "SQUAD" },
    { name: "Ambati Rayudu", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2013, ipls: ["MI","CSK"], wc: "SQUAD" },
    { name: "Robin Uthappa", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2006, ipls: ["MI","RCB","PWI","KKR","RR","CSK"], wc: "WON" },
    { name: "Dinesh Karthik", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2004, ipls: ["DC","PBKS","MI","RCB","GL","KKR"], wc: "WON" },
    { name: "Manish Pandey", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2015, ipls: ["MI","RCB","PWI","KKR","SRH","LSG","DC"], wc: "SQUAD" },
    { name: "Kedar Jadhav", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2014, ipls: ["DC","KTK","RCB","CSK","SRH"], wc: "SQUAD" },
    { name: "Deepak Chahar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2018, ipls: ["RPS","CSK","MI"], wc: "NEVER" },
    { name: "Washington Sundar", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2017, ipls: ["RPS","RCB","SRH","GT"], wc: "WON" },
    { name: "Axar Patel", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2014, ipls: ["PBKS","DC"], wc: "WON" },
    { name: "Shardul Thakur", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2017, ipls: ["PBKS","RPS","CSK","DC","KKR","LSG","MI"], wc: "SQUAD" },
    { name: "T Natarajan", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2020, ipls: ["PBKS","SRH","DC"], wc: "SQUAD" },
    { name: "Varun Chakravarthy", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2021, ipls: ["KKR"], wc: "WON" },
    { name: "Arshdeep Singh", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2022, ipls: ["PBKS"], wc: "WON" },
    { name: "Umran Malik", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2022, ipls: ["SRH"], wc: "NEVER" },
    { name: "Prasidh Krishna", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2021, ipls: ["KKR","RR","GT"], wc: "NEVER" },
    { name: "Tilak Varma", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2023, ipls: ["MI"], wc: "WON" },
    { name: "Ruturaj Gaikwad", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2021, ipls: ["CSK"], wc: "NEVER" },
    { name: "Ishan Kishan", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2021, ipls: ["GL","MI","SRH"], wc: "WON" },
    { name: "Sanju Samson", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipls: ["KKR","RR","DC","CSK"], wc: "WON" },
    { name: "Prithvi Shaw", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2018, ipls: ["DC"], wc: "NEVER" },
    { name: "Venkatesh Iyer", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2021, ipls: ["KKR","RCB"], wc: "NEVER" },
    { name: "Rinku Singh", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipls: ["PBKS","KKR"], wc: "WON" },
    { name: "Yashasvi Jaiswal", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipls: ["RR"], wc: "WON" },
    { name: "Krunal Pandya", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2018, ipls: ["MI","LSG","RCB"], wc: "NEVER" },
    { name: "Piyush Chawla", country: "India", role: "Bowler", bat: "Left", bowl: "Legbreak", debut: 2006, ipls: ["PBKS","KKR","CSK","MI"], wc: "WON" },
    { name: "Amit Mishra", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2003, ipls: ["DC","DECCAN","SRH","LSG"], wc: "SQUAD" },
    { name: "Pragyan Ojha", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 2008, ipls: ["DECCAN","MI","SRH"], wc: "SQUAD" },
    { name: "Munaf Patel", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2006, ipls: ["RR","MI","GL"], wc: "WON" },
    { name: "Irfan Pathan", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm fast-medium", debut: 2003, ipls: ["PBKS","DC","SRH","RPS","GL"], wc: "WON" },
    { name: "Yusuf Pathan", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipls: ["RR","KKR","SRH"], wc: "WON" },
    { name: "RP Singh", country: "India", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2005, ipls: ["DECCAN","KTK","MI","RCB","RPS","SRH"], wc: "WON" },
    { name: "Praveen Kumar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2007, ipls: ["RCB","PBKS","MI","SRH","GL"], wc: "SQUAD" },
    { name: "S Sreesanth", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2005, ipls: ["PBKS","KTK","RR"], wc: "WON" },
    { name: "Wriddhiman Saha", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2010, ipls: ["KKR","CSK","PBKS","SRH","GT"], wc: "NEVER" },
    { name: "Murali Vijay", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipls: ["CSK","DC","PBKS"], wc: "SQUAD" },
    { name: "Parthiv Patel", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2002, ipls: ["CSK","KTK","DECCAN","SRH","RCB","MI"], wc: "SQUAD" },
    { name: "Mohit Sharma", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2013, ipls: ["CSK","PBKS","DC","GT"], wc: "SQUAD" },
    { name: "Navdeep Saini", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipls: ["RCB","RR","KKR"], wc: "NEVER" },
    { name: "Abhishek Sharma", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2024, ipls: ["DC","SRH"], wc: "WON" },
    { name: "Sai Sudharsan", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipls: ["GT"], wc: "NEVER" },
    { name: "Nitish Kumar Reddy", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2024, ipls: ["SRH"], wc: "NEVER" },
    { name: "Dhruv Jurel", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2024, ipls: ["RR"], wc: "NEVER" },
    { name: "Shivam Dube", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2019, ipls: ["RCB","RR","CSK"], wc: "WON" },
    { name: "Ravi Bishnoi", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2022, ipls: ["PBKS","LSG","RR"], wc: "NEVER" },
    { name: "Sarfaraz Khan", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2024, ipls: ["RCB","PBKS","DC","CSK"], wc: "NEVER" },
    { name: "Rajat Patidar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2023, ipls: ["RCB"], wc: "NEVER" },
    { name: "Jitesh Sharma", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2023, ipls: ["PBKS","RCB"], wc: "NEVER" },
    { name: "Riyan Parag", country: "India", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2024, ipls: ["RR"], wc: "NEVER" },
    { name: "Harshal Patel", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2021, ipls: ["RCB","DC","PBKS","SRH"], wc: "SQUAD" },
    { name: "Avesh Khan", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2022, ipls: ["RCB","DC","LSG","RR"], wc: "SQUAD" },
    { name: "Khaleel Ahmed", country: "India", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2018, ipls: ["SRH","DC","CSK"], wc: "SQUAD" },
    { name: "Ajit Agarkar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 1998, ipls: ["KKR","DC"], wc: "WON" },
    { name: "Harshit Rana", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2024, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Vaibhav Suryavanshi", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2026, ipls: ["RR"], wc: "NEVER" },
    { name: "Suresh Raina", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2005, ipls: ["CSK","GL"], wc: "WON" },
    { name: "Umesh Yadav", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2010, ipls: ["DC","KKR","RCB","GT"], wc: "SQUAD" },
    { name: "Mayank Agarwal", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2018, ipls: ["RCB","DC","RPS","PBKS","SRH"], wc: "SQUAD" },
    { name: "Sunil Gavaskar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1971, ipls: [], wc: "WON" },
    { name: "Kapil Dev", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1978, ipls: [], wc: "WON" },
    { name: "Bishan Singh Bedi", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 1966, ipls: [], wc: "SQUAD" },
    { name: "Gundappa Viswanath", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1969, ipls: [], wc: "SQUAD" },
    { name: "Mohinder Amarnath", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 1969, ipls: [], wc: "WON" },
    { name: "Dilip Vengsarkar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1976, ipls: [], wc: "WON" },
    { name: "Erapalli Prasanna", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1962, ipls: [], wc: "NEVER" },
    { name: "Mohammad Azharuddin", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1984, ipls: [], wc: "SQUAD" },
    { name: "Navjot Singh Sidhu", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1983, ipls: [], wc: "SQUAD" },
    { name: "Javagal Srinath", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1991, ipls: [], wc: "SQUAD" },
    { name: "Ravi Shastri", country: "India", role: "Allrounder", bat: "Right", bowl: "Left-arm orthodox", debut: 1981, ipls: [], wc: "WON" },
    { name: "Kris Srikkanth", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1981, ipls: [], wc: "WON" },
    // ---------- AUSTRALIA ----------
    { name: "Ricky Ponting", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1995, ipls: ["KKR","MI"], wc: "WON" },
    { name: "Adam Gilchrist", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 1996, ipls: ["DECCAN","PBKS"], wc: "WON" },
    { name: "Shane Warne", country: "Australia", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1992, ipls: ["RR"], wc: "WON" },
    { name: "Glenn McGrath", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 1993, ipls: ["DC"], wc: "WON" },
    { name: "Michael Hussey", country: "Australia", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2004, ipls: ["CSK","MI"], wc: "WON" },
    { name: "Michael Clarke", country: "Australia", role: "Batter", bat: "Right", bowl: "Left-arm orthodox", debut: 2003, ipls: ["PWI","PBKS"], wc: "WON" },
    { name: "Shane Watson", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2002, ipls: ["RR","RCB","CSK"], wc: "WON" },
    { name: "Brett Lee", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1999, ipls: ["PBKS","KKR"], wc: "WON" },
    { name: "David Warner", country: "Australia", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 2009, ipls: ["DC","SRH"], wc: "WON" },
    { name: "Steve Smith", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipls: ["PWI","RR","RPS","DC"], wc: "WON" },
    { name: "Glenn Maxwell", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2012, ipls: ["DC","MI","PBKS","RCB"], wc: "WON" },
    { name: "Pat Cummins", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2011, ipls: ["KKR","DC","SRH"], wc: "WON" },
    { name: "Mitchell Starc", country: "Australia", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2010, ipls: ["RCB","KKR","DC"], wc: "WON" },
    { name: "Josh Hazlewood", country: "Australia", role: "Bowler", bat: "Left", bowl: "Right-arm fast-medium", debut: 2010, ipls: ["CSK","RCB"], wc: "WON" },
    { name: "Marcus Stoinis", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2015, ipls: ["PBKS","RCB","DC","LSG"], wc: "WON" },
    { name: "Aaron Finch", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2011, ipls: ["RR","DC","PWI","SRH","MI","GL","PBKS","RCB","KKR"], wc: "WON" },
    { name: "Travis Head", country: "Australia", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2016, ipls: ["RCB","SRH"], wc: "WON" },
    { name: "Cameron Green", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2020, ipls: ["MI","RCB","KKR"], wc: "WON" },
    { name: "Adam Zampa", country: "Australia", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2016, ipls: ["RPS","RCB","RR","SRH"], wc: "WON" },
    { name: "Tim David", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2019, ipls: ["RCB","MI"], wc: "SQUAD" },
    { name: "Nathan Coulter-Nile", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2013, ipls: ["MI","DC","KKR","RR"], wc: "SQUAD" },
    { name: "Allan Border", country: "Australia", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 1978, ipls: [], wc: "WON" },
    { name: "Steve Waugh", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1985, ipls: [], wc: "WON" },
    { name: "Mark Waugh", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1988, ipls: [], wc: "WON" },
    { name: "Dennis Lillee", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1971, ipls: [], wc: "SQUAD" },
    { name: "Matthew Hayden", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 1993, ipls: ["CSK"], wc: "WON" },
    { name: "Justin Langer", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 1993, ipls: ["RR"], wc: "NEVER" },
    { name: "Rodney Marsh", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 1970, ipls: [], wc: "SQUAD" },
    { name: "Mitchell Marsh", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipls: ["DECCAN","PWI","RPS","SRH","DC","LSG"], wc: "WON" },
    { name: "Nathan Lyon", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2011, ipls: [], wc: "SQUAD" },
    { name: "Usman Khawaja", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 2011, ipls: ["RPS"], wc: "SQUAD" },
    { name: "Marnus Labuschagne", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2018, ipls: [], wc: "WON" },
    { name: "Alex Carey", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 2018, ipls: ["DC"], wc: "WON" },
    { name: "Josh Inglis", country: "Australia", role: "Keeper", bat: "Right", bowl: "—", debut: 2022, ipls: ["PBKS","LSG"], wc: "WON" },
    { name: "Sean Abbott", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2014, ipls: ["RCB","SRH"], wc: "WON" },
    { name: "Matthew Wade", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 2011, ipls: ["DC","GT"], wc: "WON" },
    { name: "Mitchell Johnson", country: "Australia", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2005, ipls: ["MI","PBKS","KKR"], wc: "WON" },
    { name: "Andrew Symonds", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 1998, ipls: ["DECCAN","MI"], wc: "WON" },
    { name: "Michael Bevan", country: "Australia", role: "Batter", bat: "Left", bowl: "Left-arm wrist-spin", debut: 1994, ipls: [], wc: "WON" },
    { name: "Jake Fraser-McGurk", country: "Australia", role: "Batter", bat: "Right", bowl: "—", debut: 2024, ipls: ["DC"], wc: "SQUAD" },
    { name: "Chris Lynn", country: "Australia", role: "Batter", bat: "Right", bowl: "—", debut: 2014, ipls: ["KKR"], wc: "NEVER" },
    // ---------- ENGLAND ----------
    { name: "Ben Stokes", country: "England", role: "Allrounder", bat: "Left", bowl: "Right-arm fast-medium", debut: 2011, ipls: ["RPS","RR","CSK"], wc: "WON" },
    { name: "Joe Root", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2012, ipls: ["RR"], wc: "WON" },
    { name: "Jos Buttler", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2011, ipls: ["MI","RR","GT"], wc: "WON" },
    { name: "Jonny Bairstow", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2011, ipls: ["SRH","PBKS","MI"], wc: "WON" },
    { name: "Eoin Morgan", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2006, ipls: ["RCB","KKR","SRH","PBKS"], wc: "WON" },
    { name: "Kevin Pietersen", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2004, ipls: ["RCB","DC","RPS"], wc: "WON" },
    { name: "Andrew Flintoff", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 1998, ipls: ["CSK"], wc: "SQUAD" },
    { name: "Moeen Ali", country: "England", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2014, ipls: ["RCB","CSK"], wc: "WON" },
    { name: "Sam Curran", country: "England", role: "Allrounder", bat: "Left", bowl: "Left-arm medium", debut: 2018, ipls: ["PBKS","CSK","RR"], wc: "WON" },
    { name: "Chris Woakes", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipls: ["KKR","RCB","DC"], wc: "WON" },
    { name: "Jofra Archer", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipls: ["RR","MI"], wc: "WON" },
    { name: "Liam Livingstone", country: "England", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipls: ["RR","PBKS","RCB","SRH"], wc: "WON" },
    { name: "Harry Brook", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2022, ipls: ["SRH","DC"], wc: "WON" },
    { name: "Phil Salt", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2021, ipls: ["DC","KKR","RCB"], wc: "SQUAD" },
    { name: "Stuart Broad", country: "England", role: "Bowler", bat: "Left", bowl: "Right-arm fast-medium", debut: 2006, ipls: [], wc: "WON" },
    { name: "James Anderson", country: "England", role: "Bowler", bat: "Left", bowl: "Right-arm fast-medium", debut: 2002, ipls: [], wc: "WON" },
    { name: "Graeme Swann", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2000, ipls: [], wc: "WON" },
    { name: "Alastair Cook", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2006, ipls: [], wc: "NEVER" },
    { name: "Ian Botham", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1976, ipls: [], wc: "SQUAD" },
    { name: "David Gower", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 1978, ipls: [], wc: "SQUAD" },
    { name: "Andrew Strauss", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2003, ipls: [], wc: "SQUAD" },
    { name: "Graham Gooch", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1975, ipls: [], wc: "SQUAD" },
    { name: "Adil Rashid", country: "England", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2009, ipls: ["PBKS","SRH"], wc: "WON" },
    { name: "Mark Wood", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2015, ipls: ["CSK","LSG"], wc: "WON" },
    { name: "Jason Roy", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2014, ipls: [], wc: "WON" },
    { name: "Dawid Malan", country: "England", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 2017, ipls: ["PBKS"], wc: "WON" },
    { name: "Ben Duckett", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Zak Crawley", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2019, ipls: [], wc: "NEVER" },
    { name: "Ollie Pope", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2018, ipls: [], wc: "NEVER" },
    { name: "Jamie Smith", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2023, ipls: [], wc: "NEVER" },
    { name: "Reece Topley", country: "England", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2015, ipls: ["RCB","MI"], wc: "SQUAD" },
    { name: "Gus Atkinson", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2023, ipls: [], wc: "SQUAD" },
    { name: "Will Jacks", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2022, ipls: ["RCB","MI"], wc: "SQUAD" },
    { name: "Jacob Bethell", country: "England", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2024, ipls: ["RCB"], wc: "SQUAD" },
    { name: "Marcus Trescothick", country: "England", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2000, ipls: [], wc: "SQUAD" },
    { name: "Michael Vaughan", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipls: [], wc: "SQUAD" },
    // ---------- SOUTH AFRICA ----------
    { name: "AB de Villiers", country: "South Africa", role: "Keeper", bat: "Right", bowl: "—", debut: 2004, ipls: ["DC","RCB"], wc: "SQUAD" },
    { name: "Jacques Kallis", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1995, ipls: ["RCB","KKR"], wc: "SQUAD" },
    { name: "Faf du Plessis", country: "South Africa", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2011, ipls: ["CSK","RPS","RCB","DC"], wc: "SQUAD" },
    { name: "Quinton de Kock", country: "South Africa", role: "Keeper", bat: "Left", bowl: "—", debut: 2012, ipls: ["SRH","DC","RCB","MI","LSG","KKR"], wc: "SQUAD" },
    { name: "Kagiso Rabada", country: "South Africa", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 2014, ipls: ["DC","PBKS","GT"], wc: "SQUAD" },
    { name: "Dale Steyn", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2004, ipls: ["RCB","DECCAN","SRH","GL"], wc: "SQUAD" },
    { name: "Hashim Amla", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 2004, ipls: ["PBKS"], wc: "SQUAD" },
    { name: "David Miller", country: "South Africa", role: "Batter", bat: "Left", bowl: "—", debut: 2010, ipls: ["PBKS","RR","GT","LSG","DC"], wc: "SQUAD" },
    { name: "Heinrich Klaasen", country: "South Africa", role: "Keeper", bat: "Right", bowl: "—", debut: 2018, ipls: ["RR","RCB","SRH"], wc: "SQUAD" },
    { name: "Aiden Markram", country: "South Africa", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipls: ["PBKS","SRH","LSG"], wc: "SQUAD" },
    { name: "Anrich Nortje", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipls: ["DC","KKR","LSG"], wc: "SQUAD" },
    { name: "Lungi Ngidi", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2017, ipls: ["CSK","DC","RCB"], wc: "SQUAD" },
    { name: "Marco Jansen", country: "South Africa", role: "Allrounder", bat: "Left", bowl: "Left-arm fast", debut: 2021, ipls: ["MI","SRH","PBKS"], wc: "SQUAD" },
    { name: "Morne Morkel", country: "South Africa", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 2006, ipls: ["RR","DC","KKR"], wc: "SQUAD" },
    { name: "Graeme Smith", country: "South Africa", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2002, ipls: ["RR","PWI"], wc: "SQUAD" },
    { name: "Tristan Stubbs", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 2022, ipls: ["MI","DC"], wc: "SQUAD" },
    { name: "Allan Donald", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1991, ipls: [], wc: "SQUAD" },
    { name: "Shaun Pollock", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1995, ipls: ["MI"], wc: "SQUAD" },
    { name: "Makhaya Ntini", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1998, ipls: ["CSK"], wc: "SQUAD" },
    { name: "Herschelle Gibbs", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 1996, ipls: ["DECCAN","MI","DC"], wc: "SQUAD" },
    { name: "Temba Bavuma", country: "South Africa", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2014, ipls: [], wc: "SQUAD" },
    { name: "Rassie van der Dussen", country: "South Africa", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2018, ipls: ["RR"], wc: "SQUAD" },
    { name: "Keshav Maharaj", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Left-arm orthodox", debut: 2016, ipls: ["RR","MI"], wc: "SQUAD" },
    { name: "Tabraiz Shamsi", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Left-arm wrist-spin", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Gerald Coetzee", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2023, ipls: ["MI","GT"], wc: "SQUAD" },
    { name: "Ryan Rickelton", country: "South Africa", role: "Keeper", bat: "Left", bowl: "—", debut: 2022, ipls: ["MI"], wc: "SQUAD" },
    { name: "Kyle Verreynne", country: "South Africa", role: "Keeper", bat: "Right", bowl: "—", debut: 2020, ipls: [], wc: "NEVER" },
    { name: "Imran Tahir", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2011, ipls: ["DC","CSK"], wc: "SQUAD" },
    { name: "Vernon Philander", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2007, ipls: [], wc: "SQUAD" },
    { name: "JP Duminy", country: "South Africa", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2004, ipls: ["MI","DECCAN","SRH","DC"], wc: "SQUAD" },
    { name: "Jonty Rhodes", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 1992, ipls: [], wc: "SQUAD" },
    { name: "Lance Klusener", country: "South Africa", role: "Allrounder", bat: "Left", bowl: "Right-arm fast-medium", debut: 1996, ipls: [], wc: "SQUAD" },
    // ---------- NEW ZEALAND ----------
    { name: "Kane Williamson", country: "New Zealand", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2010, ipls: ["SRH","GT"], wc: "SQUAD" },
    { name: "Trent Boult", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2011, ipls: ["SRH","KKR","DC","MI","RR"], wc: "SQUAD" },
    { name: "Tim Southee", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2008, ipls: ["CSK","RR","MI","RCB","KKR"], wc: "SQUAD" },
    { name: "Ross Taylor", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2006, ipls: ["RCB","RR","DC","PWI"], wc: "SQUAD" },
    { name: "Brendon McCullum", country: "New Zealand", role: "Keeper", bat: "Right", bowl: "—", debut: 2002, ipls: ["KKR","KTK","CSK","GL","RCB"], wc: "SQUAD" },
    { name: "Daniel Vettori", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1997, ipls: ["DC","RCB"], wc: "SQUAD" },
    { name: "Martin Guptill", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2009, ipls: ["MI","PBKS","SRH"], wc: "SQUAD" },
    { name: "Mitchell Santner", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2015, ipls: ["CSK","MI"], wc: "SQUAD" },
    { name: "Lockie Ferguson", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipls: ["RPS","KKR","GT","RCB","PBKS"], wc: "SQUAD" },
    { name: "Devon Conway", country: "New Zealand", role: "Keeper", bat: "Left", bowl: "—", debut: 2020, ipls: ["CSK"], wc: "SQUAD" },
    { name: "Glenn Phillips", country: "New Zealand", role: "Keeper", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipls: ["RR","SRH","GT"], wc: "SQUAD" },
    { name: "James Neesham", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2012, ipls: [], wc: "SQUAD" },
    { name: "Stephen Fleming", country: "New Zealand", role: "Batter", bat: "Left", bowl: "—", debut: 1994, ipls: ["CSK"], wc: "SQUAD" },
    { name: "Richard Hadlee", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm fast-medium", debut: 1973, ipls: [], wc: "SQUAD" },
    { name: "Rachin Ravindra", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2021, ipls: ["CSK","KKR"], wc: "SQUAD" },
    { name: "Kyle Jamieson", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2020, ipls: ["RCB","PBKS","DC"], wc: "SQUAD" },
    { name: "Matt Henry", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2014, ipls: ["PBKS","LSG","CSK"], wc: "SQUAD" },
    { name: "Tom Latham", country: "New Zealand", role: "Keeper", bat: "Left", bowl: "—", debut: 2012, ipls: [], wc: "SQUAD" },
    { name: "Daryl Mitchell", country: "New Zealand", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2019, ipls: ["RR","CSK"], wc: "SQUAD" },
    { name: "Michael Bracewell", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2022, ipls: ["RCB"], wc: "SQUAD" },
    { name: "Ish Sodhi", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2013, ipls: ["RR"], wc: "SQUAD" },
    { name: "Finn Allen", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2021, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Henry Nicholls", country: "New Zealand", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2015, ipls: [], wc: "SQUAD" },
    { name: "Colin de Grandhomme", country: "New Zealand", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2012, ipls: ["KKR","RCB"], wc: "SQUAD" },
    { name: "Shane Bond", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2001, ipls: ["KKR"], wc: "SQUAD" },
    // ---------- WEST INDIES ----------
    { name: "Chris Gayle", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 1999, ipls: ["KKR","RCB","PBKS"], wc: "WON" },
    { name: "Dwayne Bravo", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2004, ipls: ["MI","CSK","GL"], wc: "WON" },
    { name: "Kieron Pollard", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2007, ipls: ["MI"], wc: "WON" },
    { name: "Sunil Narine", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2011, ipls: ["KKR"], wc: "WON" },
    { name: "Andre Russell", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 2010, ipls: ["DC","KKR"], wc: "WON" },
    { name: "Nicholas Pooran", country: "West Indies", role: "Keeper", bat: "Left", bowl: "—", debut: 2016, ipls: ["PBKS","LSG"], wc: "SQUAD" },
    { name: "Shimron Hetmyer", country: "West Indies", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipls: ["RCB","DC","RR"], wc: "SQUAD" },
    { name: "Jason Holder", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2013, ipls: ["CSK","SRH","KKR","LSG","RR","GT"], wc: "SQUAD" },
    { name: "Evin Lewis", country: "West Indies", role: "Batter", bat: "Left", bowl: "—", debut: 2016, ipls: ["MI","RR","LSG"], wc: "WON" },
    { name: "Marlon Samuels", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2000, ipls: ["PWI","DC"], wc: "WON" },
    { name: "Carlos Brathwaite", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipls: ["DC","SRH","KKR"], wc: "WON" },
    { name: "Brian Lara", country: "West Indies", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 1990, ipls: [], wc: "SQUAD" },
    { name: "Viv Richards", country: "West Indies", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1974, ipls: [], wc: "WON" },
    { name: "Garfield Sobers", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1954, ipls: [], wc: "NEVER" },
    { name: "Malcolm Marshall", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1978, ipls: [], wc: "WON" },
    { name: "Curtly Ambrose", country: "West Indies", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 1988, ipls: [], wc: "SQUAD" },
    { name: "Courtney Walsh", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1984, ipls: [], wc: "SQUAD" },
    { name: "Michael Holding", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1975, ipls: [], wc: "WON" },
    { name: "Clive Lloyd", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1966, ipls: [], wc: "WON" },
    { name: "Gordon Greenidge", country: "West Indies", role: "Batter", bat: "Right", bowl: "—", debut: 1974, ipls: [], wc: "WON" },
    { name: "Shivnarine Chanderpaul", country: "West Indies", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 1994, ipls: ["RCB"], wc: "SQUAD" },
    { name: "Rovman Powell", country: "West Indies", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2016, ipls: ["DC","RR","KKR"], wc: "SQUAD" },
    { name: "Shai Hope", country: "West Indies", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipls: ["DC"], wc: "SQUAD" },
    { name: "Alzarri Joseph", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipls: ["MI","GT","RCB"], wc: "SQUAD" },
    { name: "Shamar Joseph", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2024, ipls: ["LSG"], wc: "SQUAD" },
    { name: "Akeal Hosein", country: "West Indies", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 2021, ipls: ["SRH","CSK"], wc: "SQUAD" },
    { name: "Kyle Mayers", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2020, ipls: ["LSG"], wc: "SQUAD" },
    { name: "Sherfane Rutherford", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2018, ipls: ["DC","RCB","GT","MI"], wc: "SQUAD" },
    { name: "Roston Chase", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Darren Sammy", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2004, ipls: ["SRH","RCB"], wc: "WON" },
    // ---------- PAKISTAN ----------
    { name: "Babar Azam", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2015, ipls: [], wc: "SQUAD" },
    { name: "Shaheen Afridi", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2018, ipls: [], wc: "SQUAD" },
    { name: "Mohammad Rizwan", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipls: [], wc: "SQUAD" },
    { name: "Shadab Khan", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipls: [], wc: "SQUAD" },
    { name: "Fakhar Zaman", country: "Pakistan", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 2017, ipls: [], wc: "SQUAD" },
    { name: "Haris Rauf", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2020, ipls: [], wc: "SQUAD" },
    { name: "Naseem Shah", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipls: [], wc: "SQUAD" },
    { name: "Shoaib Malik", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipls: ["DC"], wc: "WON" },
    { name: "Shahid Afridi", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 1996, ipls: ["DECCAN","DC"], wc: "WON" },
    { name: "Shoaib Akhtar", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1997, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Sohail Tanvir", country: "Pakistan", role: "Allrounder", bat: "Left", bowl: "Left-arm fast-medium", debut: 2007, ipls: ["RR"], wc: "WON" },
    { name: "Umar Gul", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2003, ipls: ["KKR"], wc: "WON" },
    { name: "Younis Khan", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2000, ipls: ["RR"], wc: "WON" },
    { name: "Misbah-ul-Haq", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 2001, ipls: ["RCB"], wc: "WON" },
    { name: "Mohammad Yousuf", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 1998, ipls: [], wc: "SQUAD" },
    { name: "Saeed Ajmal", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipls: [], wc: "WON" },
    { name: "Wasim Akram", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 1984, ipls: [], wc: "WON" },
    { name: "Waqar Younis", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1989, ipls: [], wc: "SQUAD" },
    { name: "Imran Khan", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 1971, ipls: [], wc: "WON" },
    { name: "Javed Miandad", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 1975, ipls: [], wc: "WON" },
    { name: "Inzamam-ul-Haq", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 1991, ipls: [], wc: "WON" },
    { name: "Saeed Anwar", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 1989, ipls: [], wc: "SQUAD" },
    { name: "Mushtaq Ahmed", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1989, ipls: [], wc: "WON" },
    { name: "Mohammad Amir", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2009, ipls: [], wc: "WON" },
    { name: "Mohammad Hafeez", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2003, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Sarfaraz Ahmed", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2007, ipls: [], wc: "SQUAD" },
    { name: "Hasan Ali", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Shan Masood", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 2013, ipls: [], wc: "SQUAD" },
    { name: "Abdullah Shafique", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 2020, ipls: [], wc: "SQUAD" },
    { name: "Saim Ayub", country: "Pakistan", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2023, ipls: [], wc: "SQUAD" },
    { name: "Abrar Ahmed", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2022, ipls: [], wc: "SQUAD" },
    { name: "Wahab Riaz", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Left-arm fast", debut: 2008, ipls: [], wc: "SQUAD" },
    { name: "Abdul Qadir", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1977, ipls: [], wc: "SQUAD" },
    { name: "Imam-ul-Haq", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipls: [], wc: "SQUAD" },
    { name: "Azhar Ali", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipls: [], wc: "SQUAD" },
    { name: "Imad Wasim", country: "Pakistan", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2015, ipls: [], wc: "SQUAD" },
    { name: "Iftikhar Ahmed", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2015, ipls: [], wc: "SQUAD" },
    { name: "Kamran Akmal", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2002, ipls: ["RR"], wc: "WON" },
    { name: "Abdul Razzaq", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1996, ipls: [], wc: "WON" },
    { name: "Saqlain Mushtaq", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1995, ipls: [], wc: "SQUAD" },
    // ---------- SRI LANKA ----------
    { name: "Kumar Sangakkara", country: "Sri Lanka", role: "Keeper", bat: "Left", bowl: "—", debut: 2000, ipls: ["PBKS","DECCAN","SRH","KKR"], wc: "WON" },
    { name: "Mahela Jayawardene", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1997, ipls: ["PBKS","KTK","DC","MI"], wc: "WON" },
    { name: "Muttiah Muralitharan", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1992, ipls: ["CSK","KTK","RCB"], wc: "WON" },
    { name: "Sanath Jayasuriya", country: "Sri Lanka", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1989, ipls: ["MI"], wc: "WON" },
    { name: "Lasith Malinga", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2004, ipls: ["MI"], wc: "WON" },
    { name: "Tillakaratne Dilshan", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipls: ["DC","RCB"], wc: "WON" },
    { name: "Angelo Mathews", country: "Sri Lanka", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2008, ipls: ["KKR","PWI","DC"], wc: "WON" },
    { name: "Ajantha Mendis", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipls: ["KKR","PWI"], wc: "WON" },
    { name: "Wanindu Hasaranga", country: "Sri Lanka", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipls: ["RCB","RR"], wc: "SQUAD" },
    { name: "Rangana Herath", country: "Sri Lanka", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 1999, ipls: [], wc: "WON" },
    { name: "Chaminda Vaas", country: "Sri Lanka", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 1994, ipls: ["DECCAN","DC"], wc: "WON" },
    { name: "Aravinda de Silva", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1984, ipls: [], wc: "WON" },
    { name: "Kusal Perera", country: "Sri Lanka", role: "Keeper", bat: "Left", bowl: "—", debut: 2013, ipls: ["RR"], wc: "WON" },
    { name: "Pathum Nissanka", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "—", debut: 2021, ipls: ["DC"], wc: "SQUAD" },
    { name: "Nuwan Kulasekara", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2003, ipls: ["CSK"], wc: "WON" },
    { name: "Kusal Mendis", country: "Sri Lanka", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipls: ["GT"], wc: "SQUAD" },
    { name: "Dinesh Chandimal", country: "Sri Lanka", role: "Keeper", bat: "Right", bowl: "—", debut: 2010, ipls: [], wc: "WON" },
    { name: "Matheesha Pathirana", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2022, ipls: ["CSK","KKR"], wc: "SQUAD" },
    { name: "Maheesh Theekshana", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2021, ipls: ["CSK","RR"], wc: "SQUAD" },
    { name: "Charith Asalanka", country: "Sri Lanka", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2021, ipls: [], wc: "SQUAD" },
    { name: "Arjuna Ranatunga", country: "Sri Lanka", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1982, ipls: [], wc: "WON" },
    // ---------- BANGLADESH ----------
    { name: "Shakib Al Hasan", country: "Bangladesh", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2006, ipls: ["KKR","SRH"], wc: "SQUAD" },
    { name: "Mushfiqur Rahim", country: "Bangladesh", role: "Keeper", bat: "Right", bowl: "—", debut: 2005, ipls: [], wc: "SQUAD" },
    { name: "Tamim Iqbal", country: "Bangladesh", role: "Batter", bat: "Left", bowl: "—", debut: 2007, ipls: [], wc: "SQUAD" },
    { name: "Mustafizur Rahman", country: "Bangladesh", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2015, ipls: ["SRH","MI","RR","DC","CSK"], wc: "SQUAD" },
    { name: "Mahmudullah", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipls: [], wc: "SQUAD" },
    { name: "Mashrafe Mortaza", country: "Bangladesh", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2001, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Litton Das", country: "Bangladesh", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Taskin Ahmed", country: "Bangladesh", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 2014, ipls: [], wc: "SQUAD" },
    { name: "Mehidy Hasan", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Najmul Hossain Shanto", country: "Bangladesh", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipls: [], wc: "SQUAD" },
    { name: "Towhid Hridoy", country: "Bangladesh", role: "Batter", bat: "Right", bowl: "—", debut: 2023, ipls: [], wc: "SQUAD" },
    { name: "Shoriful Islam", country: "Bangladesh", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2021, ipls: [], wc: "SQUAD" },
    { name: "Rishad Hossain", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2023, ipls: [], wc: "SQUAD" },
    { name: "Mohammad Ashraful", country: "Bangladesh", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2001, ipls: ["MI"], wc: "SQUAD" },
    // ---------- AFGHANISTAN ----------
    { name: "Rashid Khan", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2015, ipls: ["SRH","GT"], wc: "SQUAD" },
    { name: "Mohammad Nabi", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2009, ipls: ["SRH"], wc: "SQUAD" },
    { name: "Mujeeb Ur Rahman", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipls: ["PBKS","SRH","MI"], wc: "SQUAD" },
    { name: "Rahmanullah Gurbaz", country: "Afghanistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2019, ipls: ["KKR"], wc: "SQUAD" },
    { name: "Noor Ahmad", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Left-arm wrist-spin", debut: 2022, ipls: ["GT","CSK"], wc: "SQUAD" },
    { name: "Fazalhaq Farooqi", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2021, ipls: ["SRH","RR"], wc: "SQUAD" },
    { name: "Ibrahim Zadran", country: "Afghanistan", role: "Batter", bat: "Right", bowl: "—", debut: 2019, ipls: [], wc: "SQUAD" },
    { name: "Naveen-ul-Haq", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipls: ["LSG"], wc: "SQUAD" },
    { name: "Azmatullah Omarzai", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2021, ipls: ["GT","PBKS"], wc: "SQUAD" },
    { name: "Mohammad Shahzad", country: "Afghanistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2009, ipls: [], wc: "SQUAD" },
    { name: "Hazratullah Zazai", country: "Afghanistan", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 2016, ipls: [], wc: "SQUAD" },
    { name: "Najibullah Zadran", country: "Afghanistan", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2012, ipls: [], wc: "SQUAD" },
    // ---------- ZIMBABWE ----------
    { name: "Sikandar Raza", country: "Zimbabwe", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2013, ipls: ["PBKS"], wc: "SQUAD" },
    { name: "Brendan Taylor", country: "Zimbabwe", role: "Keeper", bat: "Right", bowl: "—", debut: 2004, ipls: [], wc: "SQUAD" },
    { name: "Andy Flower", country: "Zimbabwe", role: "Keeper", bat: "Left", bowl: "—", debut: 1992, ipls: [], wc: "SQUAD" },
    { name: "Heath Streak", country: "Zimbabwe", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1993, ipls: [], wc: "SQUAD" },
    { name: "Sean Williams", country: "Zimbabwe", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2005, ipls: [], wc: "SQUAD" },
    { name: "Blessing Muzarabani", country: "Zimbabwe", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2017, ipls: ["RCB","KKR"], wc: "SQUAD" },
    // ---------- IRELAND ----------
    { name: "Paul Stirling", country: "Ireland", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipls: [], wc: "SQUAD" },
    { name: "Kevin O'Brien", country: "Ireland", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2006, ipls: [], wc: "SQUAD" },
    { name: "Andrew Balbirnie", country: "Ireland", role: "Batter", bat: "Right", bowl: "—", debut: 2010, ipls: [], wc: "SQUAD" },
    { name: "Josh Little", country: "Ireland", role: "Bowler", bat: "Right", bowl: "Left-arm fast", debut: 2016, ipls: ["GT"], wc: "SQUAD" },
    // ---------- NETHERLANDS ----------
    { name: "Bas de Leede", country: "Netherlands", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2018, ipls: [], wc: "SQUAD" },
    { name: "Scott Edwards", country: "Netherlands", role: "Keeper", bat: "Right", bowl: "—", debut: 2017, ipls: [], wc: "SQUAD" },
    // ---------- USA ----------
    { name: "Saurabh Netravalkar", country: "USA", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2019, ipls: [], wc: "SQUAD" },
    { name: "Aaron Jones", country: "USA", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2019, ipls: [], wc: "SQUAD" }
  ];
  root.CRICKETERS = C;
})(typeof window !== "undefined" ? window : this);
