/* Guess the Cricketer — player database
 * Compiled from general cricket knowledge. Facts only: no images, no scraped content.
 * Fields:
 *   name         display name
 *   country      full country name (region grouping drives "close" feedback)
 *   role         Batter | Bowler | Allrounder | Keeper
 *   bat          Right | Left        (batting hand)
 *   bowl         canonical bowling style string, or "—"
 *   debut        year of international debut (any format)
 *   ipl          main IPL franchise abbreviation, or "—" for non-IPL
 *   num          well-known shirt number, or null
 *
 * IPL Mode pool  = every player whose ipl !== "—"  (recognisable, easy front door)
 * Legend Mode pool = the full list, cross-era (hard mode for r/Cricket)
 *
 * Canonical bowling styles (family = pace | spin | none):
 *   pace: Right-arm fast, Right-arm fast-medium, Right-arm medium,
 *         Left-arm fast, Left-arm fast-medium, Left-arm medium
 *   spin: Right-arm offbreak, Legbreak, Left-arm orthodox, Left-arm wrist-spin
 *
 * Shirt numbers: white-ball international number preferred; a famous IPL number is
 * used where that is the player's identity. Pre-numbering-era players stay null,
 * as do players whose number could not be verified (a wrong number is worse than null).
 */
(function (root) {
  var C = [
    // ---------- INDIA — modern / IPL era ----------
    { name: "Virat Kohli", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2008, ipl: "RCB", num: 18 },
    { name: "Rohit Sharma", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipl: "MI", num: 45 },
    { name: "MS Dhoni", country: "India", role: "Keeper", bat: "Right", bowl: "Right-arm medium", debut: 2004, ipl: "CSK", num: 7 },
    { name: "Sachin Tendulkar", country: "India", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 1989, ipl: "MI", num: 10 },
    { name: "Rahul Dravid", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1996, ipl: "RR", num: 19 },
    { name: "Sourav Ganguly", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1992, ipl: "KKR", num: null },
    { name: "VVS Laxman", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1996, ipl: "SRH", num: null },
    { name: "Virender Sehwag", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipl: "DC", num: 44 },
    { name: "Yuvraj Singh", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2000, ipl: "PBKS", num: 12 },
    { name: "Gautam Gambhir", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2003, ipl: "KKR", num: 5 },
    { name: "Zaheer Khan", country: "India", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2000, ipl: "MI", num: 34 },
    { name: "Harbhajan Singh", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1998, ipl: "MI", num: 3 },
    { name: "Anil Kumble", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1990, ipl: "RCB", num: null },
    { name: "Jasprit Bumrah", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipl: "MI", num: 93 },
    { name: "Ravindra Jadeja", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2009, ipl: "CSK", num: 8 },
    { name: "Ravichandran Ashwin", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2010, ipl: "CSK", num: 99 },
    { name: "KL Rahul", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2014, ipl: "LSG", num: 1 },
    { name: "Shikhar Dhawan", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2010, ipl: "PBKS", num: 42 },
    { name: "Rishabh Pant", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2017, ipl: "DC", num: 17 },
    { name: "Shreyas Iyer", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2017, ipl: "KKR", num: 41 },
    { name: "Hardik Pandya", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipl: "MI", num: 33 },
    { name: "Mohammed Shami", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2013, ipl: "GT", num: 11 },
    { name: "Bhuvneshwar Kumar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2012, ipl: "SRH", num: 15 },
    { name: "Yuzvendra Chahal", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2016, ipl: "RR", num: 3 },
    { name: "Kuldeep Yadav", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm wrist-spin", debut: 2017, ipl: "DC", num: 23 },
    { name: "Suryakumar Yadav", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2021, ipl: "MI", num: 63 },
    { name: "Shubman Gill", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2019, ipl: "GT", num: 77 },
    { name: "Mohammed Siraj", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2017, ipl: "RCB", num: 73 },
    { name: "Ishant Sharma", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2007, ipl: "DC", num: 97 },
    { name: "Cheteshwar Pujara", country: "India", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipl: "—", num: 25 },
    { name: "Ajinkya Rahane", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2011, ipl: "CSK", num: 3 },
    { name: "Ambati Rayudu", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2013, ipl: "CSK", num: null },
    { name: "Robin Uthappa", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2006, ipl: "KKR", num: 77 },
    { name: "Dinesh Karthik", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2004, ipl: "RCB", num: 21 },
    { name: "Manish Pandey", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2015, ipl: "SRH", num: 21 },
    { name: "Kedar Jadhav", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2014, ipl: "CSK", num: 79 },
    { name: "Deepak Chahar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2018, ipl: "CSK", num: 90 },
    { name: "Washington Sundar", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2017, ipl: "SRH", num: 5 },
    { name: "Axar Patel", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2014, ipl: "DC", num: 20 },
    { name: "Shardul Thakur", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2017, ipl: "CSK", num: 54 },
    { name: "T Natarajan", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2020, ipl: "SRH", num: 4 },
    { name: "Varun Chakravarthy", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2021, ipl: "KKR", num: 29 },
    { name: "Arshdeep Singh", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2022, ipl: "PBKS", num: 2 },
    { name: "Umran Malik", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2022, ipl: "SRH", num: 21 },
    { name: "Prasidh Krishna", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2021, ipl: "RR", num: 24 },
    { name: "Tilak Varma", country: "India", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2023, ipl: "MI", num: 72 },
    { name: "Ruturaj Gaikwad", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2021, ipl: "CSK", num: 31 },
    { name: "Ishan Kishan", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2021, ipl: "MI", num: 32 },
    { name: "Sanju Samson", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipl: "RR", num: 9 },
    { name: "Prithvi Shaw", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2018, ipl: "DC", num: 100 },
    { name: "Venkatesh Iyer", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2021, ipl: "KKR", num: null },
    { name: "Rinku Singh", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipl: "KKR", num: 35 },
    { name: "Yashasvi Jaiswal", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipl: "RR", num: 64 },
    { name: "Krunal Pandya", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2018, ipl: "LSG", num: 24 },
    { name: "Piyush Chawla", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2006, ipl: "KKR", num: null },
    { name: "Amit Mishra", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2003, ipl: "DC", num: null },
    { name: "Pragyan Ojha", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 2008, ipl: "SRH", num: null },
    { name: "Munaf Patel", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2006, ipl: "MI", num: null },
    { name: "Irfan Pathan", country: "India", role: "Allrounder", bat: "Left", bowl: "Left-arm fast-medium", debut: 2003, ipl: "PBKS", num: null },
    { name: "Yusuf Pathan", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipl: "KKR", num: null },
    { name: "RP Singh", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2005, ipl: "SRH", num: null },
    { name: "Praveen Kumar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2007, ipl: "RCB", num: null },
    { name: "S Sreesanth", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2005, ipl: "RR", num: null },
    { name: "Wriddhiman Saha", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2010, ipl: "GT", num: null },
    { name: "Murali Vijay", country: "India", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2010, ipl: "CSK", num: null },
    { name: "Parthiv Patel", country: "India", role: "Keeper", bat: "Left", bowl: "—", debut: 2002, ipl: "MI", num: null },
    { name: "Mohit Sharma", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2013, ipl: "GT", num: null },
    { name: "Navdeep Saini", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipl: "RCB", num: 96 },
    { name: "Abhishek Sharma", country: "India", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 2024, ipl: "SRH", num: 4 },
    { name: "Sai Sudharsan", country: "India", role: "Batter", bat: "Left", bowl: "—", debut: 2023, ipl: "GT", num: 66 },
    { name: "Nitish Kumar Reddy", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2024, ipl: "SRH", num: 88 },
    { name: "Dhruv Jurel", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2024, ipl: "RR", num: null },
    { name: "Shivam Dube", country: "India", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2019, ipl: "CSK", num: 25 },
    { name: "Ravi Bishnoi", country: "India", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2022, ipl: "LSG", num: 56 },
    { name: "Sarfaraz Khan", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2024, ipl: "CSK", num: 97 },
    { name: "Rajat Patidar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 2023, ipl: "RCB", num: null },
    { name: "Jitesh Sharma", country: "India", role: "Keeper", bat: "Right", bowl: "—", debut: 2023, ipl: "PBKS", num: 99 },
    { name: "Riyan Parag", country: "India", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2024, ipl: "RR", num: 12 },
    { name: "Harshal Patel", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2021, ipl: "RCB", num: null },
    { name: "Avesh Khan", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2022, ipl: "LSG", num: null },
    { name: "Khaleel Ahmed", country: "India", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2018, ipl: "DC", num: null },
    { name: "Ajit Agarkar", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 1998, ipl: "KKR", num: null },

    // ---------- INDIA — legends (pre-IPL, cross-era) ----------
    { name: "Sunil Gavaskar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1971, ipl: "—", num: null },
    { name: "Kapil Dev", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1978, ipl: "—", num: null },
    { name: "Bishan Singh Bedi", country: "India", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 1966, ipl: "—", num: null },
    { name: "Gundappa Viswanath", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1969, ipl: "—", num: null },
    { name: "Mohinder Amarnath", country: "India", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 1969, ipl: "—", num: null },
    { name: "Dilip Vengsarkar", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1976, ipl: "—", num: null },
    { name: "Erapalli Prasanna", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1962, ipl: "—", num: null },
    { name: "Mohammad Azharuddin", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1984, ipl: "—", num: null },
    { name: "Navjot Singh Sidhu", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1987, ipl: "—", num: null },
    { name: "Javagal Srinath", country: "India", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1991, ipl: "—", num: null },
    { name: "Ravi Shastri", country: "India", role: "Allrounder", bat: "Right", bowl: "Left-arm orthodox", debut: 1981, ipl: "—", num: null },
    { name: "Kris Srikkanth", country: "India", role: "Batter", bat: "Right", bowl: "—", debut: 1981, ipl: "—", num: null },

    // ---------- AUSTRALIA ----------
    { name: "Ricky Ponting", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1995, ipl: "MI", num: 14 },
    { name: "Adam Gilchrist", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 1996, ipl: "PBKS", num: 18 },
    { name: "Shane Warne", country: "Australia", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1992, ipl: "RR", num: null },
    { name: "Glenn McGrath", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 1993, ipl: "DC", num: null },
    { name: "Michael Hussey", country: "Australia", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2004, ipl: "CSK", num: 48 },
    { name: "Michael Clarke", country: "Australia", role: "Batter", bat: "Right", bowl: "Left-arm orthodox", debut: 2003, ipl: "PBKS", num: 23 },
    { name: "Shane Watson", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2002, ipl: "RR", num: 33 },
    { name: "Brett Lee", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1999, ipl: "KKR", num: 58 },
    { name: "David Warner", country: "Australia", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 2009, ipl: "SRH", num: 31 },
    { name: "Steve Smith", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipl: "RR", num: 49 },
    { name: "Glenn Maxwell", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2012, ipl: "RCB", num: 32 },
    { name: "Pat Cummins", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2011, ipl: "SRH", num: 30 },
    { name: "Mitchell Starc", country: "Australia", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2010, ipl: "KKR", num: 56 },
    { name: "Josh Hazlewood", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2010, ipl: "RCB", num: 38 },
    { name: "Marcus Stoinis", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2015, ipl: "LSG", num: 17 },
    { name: "Aaron Finch", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2011, ipl: "RCB", num: 5 },
    { name: "Travis Head", country: "Australia", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2016, ipl: "SRH", num: 62 },
    { name: "Cameron Green", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2020, ipl: "RCB", num: 42 },
    { name: "Adam Zampa", country: "Australia", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2016, ipl: "RR", num: 88 },
    { name: "Tim David", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2021, ipl: "MI", num: 85 },
    { name: "Nathan Coulter-Nile", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2013, ipl: "MI", num: null },
    { name: "Allan Border", country: "Australia", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 1978, ipl: "—", num: null },
    { name: "Steve Waugh", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1985, ipl: "—", num: null },
    { name: "Mark Waugh", country: "Australia", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1988, ipl: "—", num: null },
    { name: "Dennis Lillee", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1971, ipl: "—", num: null },
    { name: "Matthew Hayden", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 1994, ipl: "CSK", num: 28 },
    { name: "Justin Langer", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 1993, ipl: "—", num: null },
    { name: "Rodney Marsh", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 1970, ipl: "—", num: null },
    { name: "Mitchell Marsh", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipl: "LSG", num: 8 },
    { name: "Nathan Lyon", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2011, ipl: "—", num: 67 },
    { name: "Usman Khawaja", country: "Australia", role: "Batter", bat: "Left", bowl: "—", debut: 2011, ipl: "—", num: 1 },
    { name: "Marnus Labuschagne", country: "Australia", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2018, ipl: "—", num: 33 },
    { name: "Alex Carey", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 2018, ipl: "DC", num: 4 },
    { name: "Josh Inglis", country: "Australia", role: "Keeper", bat: "Right", bowl: "—", debut: 2022, ipl: "PBKS", num: null },
    { name: "Sean Abbott", country: "Australia", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2014, ipl: "—", num: 77 },
    { name: "Matthew Wade", country: "Australia", role: "Keeper", bat: "Left", bowl: "—", debut: 2011, ipl: "—", num: null },
    { name: "Mitchell Johnson", country: "Australia", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2005, ipl: "MI", num: 25 },
    { name: "Andrew Symonds", country: "Australia", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 1998, ipl: "—", num: 63 },
    { name: "Michael Bevan", country: "Australia", role: "Batter", bat: "Left", bowl: "Left-arm wrist-spin", debut: 1994, ipl: "—", num: null },
    { name: "Jake Fraser-McGurk", country: "Australia", role: "Batter", bat: "Right", bowl: "—", debut: 2024, ipl: "DC", num: null },

    // ---------- ENGLAND ----------
    { name: "Ben Stokes", country: "England", role: "Allrounder", bat: "Left", bowl: "Right-arm fast-medium", debut: 2011, ipl: "CSK", num: 55 },
    { name: "Joe Root", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2012, ipl: "—", num: 66 },
    { name: "Jos Buttler", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2011, ipl: "RR", num: 63 },
    { name: "Jonny Bairstow", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2011, ipl: "SRH", num: 51 },
    { name: "Eoin Morgan", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2006, ipl: "KKR", num: 16 },
    { name: "Kevin Pietersen", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2004, ipl: "RCB", num: 24 },
    { name: "Andrew Flintoff", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 1998, ipl: "CSK", num: 11 },
    { name: "Moeen Ali", country: "England", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2014, ipl: "CSK", num: 18 },
    { name: "Sam Curran", country: "England", role: "Allrounder", bat: "Left", bowl: "Left-arm medium", debut: 2018, ipl: "PBKS", num: 58 },
    { name: "Chris Woakes", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipl: "DC", num: 19 },
    { name: "Jofra Archer", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipl: "RR", num: 22 },
    { name: "Liam Livingstone", country: "England", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipl: "PBKS", num: 23 },
    { name: "Harry Brook", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2022, ipl: "DC", num: 88 },
    { name: "Phil Salt", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2021, ipl: "RCB", num: 61 },
    { name: "Stuart Broad", country: "England", role: "Bowler", bat: "Left", bowl: "Right-arm fast-medium", debut: 2006, ipl: "—", num: 8 },
    { name: "James Anderson", country: "England", role: "Bowler", bat: "Left", bowl: "Right-arm fast-medium", debut: 2002, ipl: "—", num: 9 },
    { name: "Graeme Swann", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2000, ipl: "—", num: 66 },
    { name: "Alastair Cook", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2006, ipl: "—", num: 26 },
    { name: "Ian Botham", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1977, ipl: "—", num: null },
    { name: "David Gower", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 1978, ipl: "—", num: null },
    { name: "Andrew Strauss", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2003, ipl: "—", num: null },
    { name: "Graham Gooch", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1975, ipl: "—", num: null },
    { name: "Adil Rashid", country: "England", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2009, ipl: "—", num: 95 },
    { name: "Mark Wood", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2015, ipl: "LSG", num: 33 },
    { name: "Jason Roy", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2014, ipl: "—", num: 20 },
    { name: "Dawid Malan", country: "England", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 2017, ipl: "—", num: 29 },
    { name: "Ben Duckett", country: "England", role: "Batter", bat: "Left", bowl: "—", debut: 2016, ipl: "—", num: 17 },
    { name: "Zak Crawley", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2019, ipl: "—", num: 6 },
    { name: "Ollie Pope", country: "England", role: "Batter", bat: "Right", bowl: "—", debut: 2018, ipl: "—", num: null },
    { name: "Jamie Smith", country: "England", role: "Keeper", bat: "Right", bowl: "—", debut: 2023, ipl: "—", num: 39 },
    { name: "Reece Topley", country: "England", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2015, ipl: "RCB", num: 38 },
    { name: "Gus Atkinson", country: "England", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2023, ipl: "—", num: 37 },
    { name: "Will Jacks", country: "England", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2022, ipl: "RCB", num: 85 },
    { name: "Jacob Bethell", country: "England", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2024, ipl: "RCB", num: null },
    { name: "Marcus Trescothick", country: "England", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2000, ipl: "—", num: 23 },
    { name: "Michael Vaughan", country: "England", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipl: "—", num: 99 },

    // ---------- SOUTH AFRICA ----------
    { name: "AB de Villiers", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 2004, ipl: "RCB", num: 17 },
    { name: "Jacques Kallis", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1995, ipl: "KKR", num: 3 },
    { name: "Faf du Plessis", country: "South Africa", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2011, ipl: "RCB", num: 18 },
    { name: "Quinton de Kock", country: "South Africa", role: "Keeper", bat: "Left", bowl: "—", debut: 2013, ipl: "MI", num: 12 },
    { name: "Kagiso Rabada", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2015, ipl: "DC", num: 25 },
    { name: "Dale Steyn", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2004, ipl: "SRH", num: 8 },
    { name: "Hashim Amla", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 2004, ipl: "PBKS", num: 1 },
    { name: "David Miller", country: "South Africa", role: "Batter", bat: "Left", bowl: "—", debut: 2010, ipl: "GT", num: 10 },
    { name: "Heinrich Klaasen", country: "South Africa", role: "Keeper", bat: "Right", bowl: "—", debut: 2018, ipl: "SRH", num: 45 },
    { name: "Aiden Markram", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipl: "SRH", num: 4 },
    { name: "Anrich Nortje", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipl: "DC", num: 20 },
    { name: "Lungi Ngidi", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2017, ipl: "CSK", num: 22 },
    { name: "Marco Jansen", country: "South Africa", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2021, ipl: "SRH", num: 70 },
    { name: "Morne Morkel", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2006, ipl: "DC", num: 65 },
    { name: "Graeme Smith", country: "South Africa", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2002, ipl: "RR", num: 15 },
    { name: "Tristan Stubbs", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 2022, ipl: "DC", num: null },
    { name: "Allan Donald", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1991, ipl: "—", num: null },
    { name: "Shaun Pollock", country: "South Africa", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1995, ipl: "MI", num: 7 },
    { name: "Makhaya Ntini", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1998, ipl: "—", num: null },
    { name: "Herschelle Gibbs", country: "South Africa", role: "Batter", bat: "Right", bowl: "—", debut: 1996, ipl: "DC", num: null },
    { name: "Temba Bavuma", country: "South Africa", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2014, ipl: "—", num: null },
    { name: "Rassie van der Dussen", country: "South Africa", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2018, ipl: "RR", num: 72 },
    { name: "Keshav Maharaj", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Left-arm orthodox", debut: 2016, ipl: "RR", num: 16 },
    { name: "Tabraiz Shamsi", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Left-arm wrist-spin", debut: 2016, ipl: "—", num: null },
    { name: "Gerald Coetzee", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2023, ipl: "MI", num: null },
    { name: "Ryan Rickelton", country: "South Africa", role: "Keeper", bat: "Left", bowl: "—", debut: 2022, ipl: "MI", num: 44 },
    { name: "Kyle Verreynne", country: "South Africa", role: "Keeper", bat: "Right", bowl: "—", debut: 2020, ipl: "—", num: 91 },
    { name: "Imran Tahir", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2011, ipl: "CSK", num: 99 },
    { name: "Vernon Philander", country: "South Africa", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2007, ipl: "—", num: 24 },
    { name: "JP Duminy", country: "South Africa", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2004, ipl: "DC", num: 21 },

    // ---------- NEW ZEALAND ----------
    { name: "Kane Williamson", country: "New Zealand", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2010, ipl: "SRH", num: 22 },
    { name: "Trent Boult", country: "New Zealand", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2011, ipl: "MI", num: 18 },
    { name: "Tim Southee", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2008, ipl: "KKR", num: 38 },
    { name: "Ross Taylor", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2006, ipl: "RCB", num: 3 },
    { name: "Brendon McCullum", country: "New Zealand", role: "Keeper", bat: "Right", bowl: "—", debut: 2002, ipl: "KKR", num: 42 },
    { name: "Daniel Vettori", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1997, ipl: "DC", num: 11 },
    { name: "Martin Guptill", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2009, ipl: "MI", num: 31 },
    { name: "Mitchell Santner", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2015, ipl: "CSK", num: 74 },
    { name: "Lockie Ferguson", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipl: "KKR", num: 69 },
    { name: "Devon Conway", country: "New Zealand", role: "Batter", bat: "Left", bowl: "—", debut: 2020, ipl: "CSK", num: 88 },
    { name: "Glenn Phillips", country: "New Zealand", role: "Keeper", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipl: "—", num: 23 },
    { name: "James Neesham", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2013, ipl: "—", num: 50 },
    { name: "Stephen Fleming", country: "New Zealand", role: "Batter", bat: "Left", bowl: "—", debut: 1994, ipl: "—", num: null },
    { name: "Richard Hadlee", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm fast-medium", debut: 1973, ipl: "—", num: null },
    { name: "Rachin Ravindra", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2021, ipl: "CSK", num: 8 },
    { name: "Kyle Jamieson", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2020, ipl: "RCB", num: null },
    { name: "Matt Henry", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2014, ipl: "—", num: 21 },
    { name: "Tom Latham", country: "New Zealand", role: "Keeper", bat: "Left", bowl: "—", debut: 2012, ipl: "—", num: 48 },
    { name: "Daryl Mitchell", country: "New Zealand", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2019, ipl: "CSK", num: 75 },
    { name: "Michael Bracewell", country: "New Zealand", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2022, ipl: "RCB", num: 4 },
    { name: "Ish Sodhi", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2013, ipl: "RR", num: 61 },
    { name: "Finn Allen", country: "New Zealand", role: "Batter", bat: "Right", bowl: "—", debut: 2021, ipl: "—", num: 16 },
    { name: "Henry Nicholls", country: "New Zealand", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2015, ipl: "—", num: 86 },
    { name: "Colin de Grandhomme", country: "New Zealand", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2012, ipl: "RCB", num: 77 },
    { name: "Shane Bond", country: "New Zealand", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2001, ipl: "KKR", num: 27 },

    // ---------- WEST INDIES ----------
    { name: "Chris Gayle", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 1999, ipl: "RCB", num: 333 },
    { name: "Dwayne Bravo", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2004, ipl: "CSK", num: 47 },
    { name: "Kieron Pollard", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2007, ipl: "MI", num: 55 },
    { name: "Sunil Narine", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2011, ipl: "KKR", num: 74 },
    { name: "Andre Russell", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 2010, ipl: "KKR", num: 12 },
    { name: "Nicholas Pooran", country: "West Indies", role: "Keeper", bat: "Left", bowl: "—", debut: 2016, ipl: "LSG", num: 29 },
    { name: "Shimron Hetmyer", country: "West Indies", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipl: "RR", num: 2 },
    { name: "Jason Holder", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2013, ipl: "SRH", num: 98 },
    { name: "Evin Lewis", country: "West Indies", role: "Batter", bat: "Left", bowl: "—", debut: 2016, ipl: "MI", num: 17 },
    { name: "Marlon Samuels", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2000, ipl: "DC", num: 7 },
    { name: "Carlos Brathwaite", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2011, ipl: "DC", num: null },
    { name: "Brian Lara", country: "West Indies", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 1990, ipl: "—", num: null },
    { name: "Viv Richards", country: "West Indies", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1974, ipl: "—", num: null },
    { name: "Garfield Sobers", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1954, ipl: "—", num: null },
    { name: "Malcolm Marshall", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1978, ipl: "—", num: null },
    { name: "Curtly Ambrose", country: "West Indies", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 1988, ipl: "—", num: null },
    { name: "Courtney Walsh", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1984, ipl: "—", num: null },
    { name: "Michael Holding", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1975, ipl: "—", num: null },
    { name: "Clive Lloyd", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1966, ipl: "—", num: null },
    { name: "Gordon Greenidge", country: "West Indies", role: "Batter", bat: "Right", bowl: "—", debut: 1974, ipl: "—", num: null },
    { name: "Shivnarine Chanderpaul", country: "West Indies", role: "Batter", bat: "Left", bowl: "Legbreak", debut: 1994, ipl: "—", num: null },
    { name: "Rovman Powell", country: "West Indies", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 2016, ipl: "DC", num: 52 },
    { name: "Shai Hope", country: "West Indies", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipl: "DC", num: 4 },
    { name: "Alzarri Joseph", country: "West Indies", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2016, ipl: "GT", num: 8 },
    { name: "Shamar Joseph", country: "West Indies", role: "Bowler", bat: "Left", bowl: "Right-arm fast", debut: 2024, ipl: "LSG", num: 70 },
    { name: "Akeal Hosein", country: "West Indies", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 2021, ipl: "—", num: 7 },
    { name: "Kyle Mayers", country: "West Indies", role: "Allrounder", bat: "Left", bowl: "Right-arm medium", debut: 2020, ipl: "LSG", num: 71 },
    { name: "Sherfane Rutherford", country: "West Indies", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 2018, ipl: "GT", num: 68 },
    { name: "Roston Chase", country: "West Indies", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2016, ipl: "—", num: 10 },

    // ---------- PAKISTAN ----------
    { name: "Babar Azam", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2015, ipl: "—", num: 56 },
    { name: "Shaheen Afridi", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2018, ipl: "—", num: 10 },
    { name: "Mohammad Rizwan", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipl: "—", num: 16 },
    { name: "Shadab Khan", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipl: "—", num: 7 },
    { name: "Fakhar Zaman", country: "Pakistan", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 2017, ipl: "—", num: 39 },
    { name: "Haris Rauf", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2020, ipl: "—", num: 97 },
    { name: "Naseem Shah", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2019, ipl: "—", num: 71 },
    { name: "Shoaib Malik", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipl: "DC", num: 18 },
    { name: "Shahid Afridi", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 1996, ipl: "DC", num: 10 },
    { name: "Shoaib Akhtar", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1997, ipl: "KKR", num: 14 },
    { name: "Sohail Tanvir", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2007, ipl: "RR", num: 33 },
    { name: "Umar Gul", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2003, ipl: "KKR", num: null },
    { name: "Younis Khan", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2000, ipl: "—", num: 75 },
    { name: "Misbah-ul-Haq", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 2001, ipl: "—", num: 22 },
    { name: "Mohammad Yousuf", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 1998, ipl: "—", num: 13 },
    { name: "Saeed Ajmal", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipl: "—", num: 50 },
    { name: "Wasim Akram", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 1985, ipl: "—", num: null },
    { name: "Waqar Younis", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 1989, ipl: "—", num: null },
    { name: "Imran Khan", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast", debut: 1971, ipl: "—", num: null },
    { name: "Javed Miandad", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 1975, ipl: "—", num: null },
    { name: "Inzamam-ul-Haq", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 1991, ipl: "—", num: null },
    { name: "Saeed Anwar", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 1989, ipl: "—", num: null },
    { name: "Mushtaq Ahmed", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1989, ipl: "—", num: null },
    { name: "Mohammad Amir", country: "Pakistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast", debut: 2009, ipl: "—", num: 5 },
    { name: "Mohammad Hafeez", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2003, ipl: "KKR", num: 8 },
    { name: "Sarfaraz Ahmed", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2007, ipl: "—", num: 54 },
    { name: "Hasan Ali", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipl: "—", num: 32 },
    { name: "Shan Masood", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 2013, ipl: "—", num: 94 },
    { name: "Abdullah Shafique", country: "Pakistan", role: "Batter", bat: "Right", bowl: "—", debut: 2020, ipl: "—", num: 57 },
    { name: "Saim Ayub", country: "Pakistan", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2023, ipl: "—", num: 63 },
    { name: "Abrar Ahmed", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 2022, ipl: "—", num: 40 },
    { name: "Wahab Riaz", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Left-arm fast", debut: 2008, ipl: "—", num: 47 },
    { name: "Abdul Qadir", country: "Pakistan", role: "Bowler", bat: "Right", bowl: "Legbreak", debut: 1977, ipl: "—", num: null },
    { name: "Imam-ul-Haq", country: "Pakistan", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipl: "—", num: 26 },
    { name: "Azhar Ali", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2010, ipl: "—", num: 79 },
    { name: "Imad Wasim", country: "Pakistan", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2015, ipl: "—", num: 9 },
    { name: "Iftikhar Ahmed", country: "Pakistan", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2015, ipl: "—", num: 95 },
    { name: "Kamran Akmal", country: "Pakistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2002, ipl: "RR", num: 23 },
    { name: "Abdul Razzaq", country: "Pakistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1996, ipl: "—", num: null },

    // ---------- SRI LANKA ----------
    { name: "Kumar Sangakkara", country: "Sri Lanka", role: "Keeper", bat: "Left", bowl: "—", debut: 2000, ipl: "KKR", num: 11 },
    { name: "Mahela Jayawardene", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm medium", debut: 1997, ipl: "MI", num: 27 },
    { name: "Muttiah Muralitharan", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 1992, ipl: "CSK", num: 8 },
    { name: "Sanath Jayasuriya", country: "Sri Lanka", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 1989, ipl: "MI", num: 7 },
    { name: "Lasith Malinga", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2004, ipl: "MI", num: 99 },
    { name: "Tillakaratne Dilshan", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1999, ipl: "RCB", num: 23 },
    { name: "Angelo Mathews", country: "Sri Lanka", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2009, ipl: "DC", num: 69 },
    { name: "Ajantha Mendis", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipl: "KKR", num: 40 },
    { name: "Wanindu Hasaranga", country: "Sri Lanka", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2017, ipl: "RCB", num: 49 },
    { name: "Rangana Herath", country: "Sri Lanka", role: "Bowler", bat: "Left", bowl: "Left-arm orthodox", debut: 1999, ipl: "—", num: 14 },
    { name: "Chaminda Vaas", country: "Sri Lanka", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 1994, ipl: "DC", num: 22 },
    { name: "Aravinda de Silva", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 1984, ipl: "—", num: null },
    { name: "Kusal Perera", country: "Sri Lanka", role: "Keeper", bat: "Left", bowl: "—", debut: 2013, ipl: "—", num: 55 },
    { name: "Pathum Nissanka", country: "Sri Lanka", role: "Batter", bat: "Right", bowl: "—", debut: 2020, ipl: "—", num: 18 },
    { name: "Nuwan Kulasekara", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm medium", debut: 2003, ipl: "CSK", num: null },
    { name: "Kusal Mendis", country: "Sri Lanka", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipl: "—", num: 13 },
    { name: "Dinesh Chandimal", country: "Sri Lanka", role: "Keeper", bat: "Right", bowl: "—", debut: 2010, ipl: "—", num: 56 },
    { name: "Matheesha Pathirana", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2022, ipl: "CSK", num: 99 },
    { name: "Maheesh Theekshana", country: "Sri Lanka", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2021, ipl: "CSK", num: 61 },
    { name: "Charith Asalanka", country: "Sri Lanka", role: "Allrounder", bat: "Left", bowl: "Right-arm offbreak", debut: 2021, ipl: "—", num: 72 },
    { name: "Arjuna Ranatunga", country: "Sri Lanka", role: "Batter", bat: "Left", bowl: "Right-arm medium", debut: 1982, ipl: "—", num: null },

    // ---------- BANGLADESH ----------
    { name: "Shakib Al Hasan", country: "Bangladesh", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2006, ipl: "KKR", num: 75 },
    { name: "Mushfiqur Rahim", country: "Bangladesh", role: "Keeper", bat: "Right", bowl: "—", debut: 2005, ipl: "—", num: 15 },
    { name: "Tamim Iqbal", country: "Bangladesh", role: "Batter", bat: "Left", bowl: "—", debut: 2007, ipl: "—", num: 28 },
    { name: "Mustafizur Rahman", country: "Bangladesh", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2015, ipl: "DC", num: 90 },
    { name: "Mahmudullah", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2007, ipl: "—", num: 30 },
    { name: "Mashrafe Mortaza", country: "Bangladesh", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2001, ipl: "KKR", num: 2 },
    { name: "Litton Das", country: "Bangladesh", role: "Keeper", bat: "Right", bowl: "—", debut: 2015, ipl: "—", num: 16 },
    { name: "Taskin Ahmed", country: "Bangladesh", role: "Bowler", bat: "Right", bowl: "Right-arm fast", debut: 2014, ipl: "—", num: 3 },
    { name: "Mehidy Hasan", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2016, ipl: "—", num: 53 },
    { name: "Najmul Hossain Shanto", country: "Bangladesh", role: "Batter", bat: "Left", bowl: "—", debut: 2017, ipl: "—", num: 99 },
    { name: "Towhid Hridoy", country: "Bangladesh", role: "Batter", bat: "Right", bowl: "—", debut: 2023, ipl: "—", num: 77 },
    { name: "Shoriful Islam", country: "Bangladesh", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2021, ipl: "—", num: 47 },
    { name: "Rishad Hossain", country: "Bangladesh", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2023, ipl: "—", num: 22 },
    { name: "Mohammad Ashraful", country: "Bangladesh", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2001, ipl: "—", num: 98 },

    // ---------- AFGHANISTAN ----------
    { name: "Rashid Khan", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Legbreak", debut: 2015, ipl: "GT", num: 19 },
    { name: "Mohammad Nabi", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2009, ipl: "SRH", num: 7 },
    { name: "Mujeeb Ur Rahman", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Right-arm offbreak", debut: 2017, ipl: "PBKS", num: 88 },
    { name: "Rahmanullah Gurbaz", country: "Afghanistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2019, ipl: "KKR", num: 21 },
    { name: "Noor Ahmad", country: "Afghanistan", role: "Bowler", bat: "Left", bowl: "Left-arm wrist-spin", debut: 2022, ipl: "CSK", num: 15 },
    { name: "Fazalhaq Farooqi", country: "Afghanistan", role: "Bowler", bat: "Left", bowl: "Left-arm fast-medium", debut: 2021, ipl: "SRH", num: 5 },
    { name: "Ibrahim Zadran", country: "Afghanistan", role: "Batter", bat: "Right", bowl: "—", debut: 2020, ipl: "—", num: 18 },
    { name: "Naveen-ul-Haq", country: "Afghanistan", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2016, ipl: "LSG", num: 78 },
    { name: "Azmatullah Omarzai", country: "Afghanistan", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 2021, ipl: "PBKS", num: 9 },
    { name: "Mohammad Shahzad", country: "Afghanistan", role: "Keeper", bat: "Right", bowl: "—", debut: 2009, ipl: "—", num: 77 },
    { name: "Hazratullah Zazai", country: "Afghanistan", role: "Batter", bat: "Left", bowl: "Left-arm orthodox", debut: 2016, ipl: "—", num: 3 },
    { name: "Najibullah Zadran", country: "Afghanistan", role: "Batter", bat: "Left", bowl: "Right-arm offbreak", debut: 2012, ipl: "—", num: 1 },

    // ---------- ZIMBABWE ----------
    { name: "Sikandar Raza", country: "Zimbabwe", role: "Allrounder", bat: "Right", bowl: "Right-arm offbreak", debut: 2013, ipl: "—", num: 24 },
    { name: "Brendan Taylor", country: "Zimbabwe", role: "Keeper", bat: "Right", bowl: "—", debut: 2004, ipl: "—", num: 1 },
    { name: "Andy Flower", country: "Zimbabwe", role: "Keeper", bat: "Left", bowl: "—", debut: 1992, ipl: "—", num: null },
    { name: "Heath Streak", country: "Zimbabwe", role: "Allrounder", bat: "Right", bowl: "Right-arm fast-medium", debut: 1993, ipl: "—", num: null },
    { name: "Sean Williams", country: "Zimbabwe", role: "Allrounder", bat: "Left", bowl: "Left-arm orthodox", debut: 2005, ipl: "—", num: 14 },
    { name: "Blessing Muzarabani", country: "Zimbabwe", role: "Bowler", bat: "Right", bowl: "Right-arm fast-medium", debut: 2017, ipl: "—", num: 40 },

    // ---------- IRELAND ----------
    { name: "Paul Stirling", country: "Ireland", role: "Batter", bat: "Right", bowl: "Right-arm offbreak", debut: 2008, ipl: "—", num: 1 },
    { name: "Kevin O'Brien", country: "Ireland", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2006, ipl: "—", num: 22 },
    { name: "Andrew Balbirnie", country: "Ireland", role: "Batter", bat: "Right", bowl: "—", debut: 2010, ipl: "—", num: 63 },
    { name: "Josh Little", country: "Ireland", role: "Bowler", bat: "Right", bowl: "Left-arm fast", debut: 2016, ipl: "GT", num: 82 },

    // ---------- NETHERLANDS ----------
    { name: "Bas de Leede", country: "Netherlands", role: "Allrounder", bat: "Right", bowl: "Right-arm medium", debut: 2018, ipl: "—", num: 5 },
    { name: "Scott Edwards", country: "Netherlands", role: "Keeper", bat: "Right", bowl: "—", debut: 2018, ipl: "—", num: 35 },

    // ---------- USA ----------
    { name: "Saurabh Netravalkar", country: "USA", role: "Bowler", bat: "Right", bowl: "Left-arm fast-medium", debut: 2019, ipl: "—", num: 20 },
    { name: "Aaron Jones", country: "USA", role: "Batter", bat: "Right", bowl: "Legbreak", debut: 2019, ipl: "—", num: 85 }
  ];

  root.CRICKETERS = C;
})(typeof window !== "undefined" ? window : this);
